version: '2'
services:
  discovery:
    image: nibu/discovery
    ports:
      - "8761:8761"
  gateway:
    image: nibu/gateway
    ports:
      - "9090:9090"
    depends_on:
      - discovery
  user-service:
    image: nibu/user-service
    ports:
      - "2222:2222"
    depends_on:
      - discovery
    links:
      - mysql-ms-01
      - rabbit-mq