version: '2'
services:
  rabbit-mq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  mysql-ms-01:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=micorservice_example
      - MYSQL_USER=spring_user
      - MYSQL_PASSWORD=12345
    volumes:
      - ./db/mysql/:/docker-entrypoint-initdb.d/:ro