spring:
  application:
    name: eureka

server:
  port: ${PORT:8761}

eureka:
  server:
    enableSelfPreservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true
    metadataMap:
          instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: false