server:
  port: ${PORT:2266}

spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/micorservice_example
    username: spring_user
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      bindings:
          userCreationBroadcasts:
            content-type: application/json
            destination: user-update-pub-sub
#          userUpdateBroadcasts:
#            destination: user-creation-pub-sub
#            content-type: application/json
#          userDeleteBroadcasts:
#            destination: user-deletion-pub-sub
#            content-type: application/json
  rabbitmq:
    addresses: localhost:5672
logging:
   pattern:
     console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
   level:
     org.springframework=WARN
     org.hibernate=WARN
eureka:
  client:
    enabled: false
